package y21

// code generated by ../gen.go

import(
	"aoc"

	"aoc/2021/d1"
	"aoc/2021/d2"
	"aoc/2021/d3"
)

type solution func(string) (string, error)

var solutions [25][2]solution

func init() {
	solutions[0][0] = d1.Part1
	solutions[0][1] = d1.Part2
	solutions[1][0] = d2.Part1
	solutions[1][1] = d2.Part2
	solutions[2][0] = d3.Part1
	solutions[2][1] = d3.Part2
}

func Solve(path string, day, part int) (string, error) {
	if part != 1 && part != 2 {
		return "", aoc.ErrUndefined
	}
	if day-1 >= len(solutions) {
		return "", aoc.ErrUndefined
	}
	if sol := solutions[day-1][part-1]; sol != nil {
		return sol(path)
	}
	return "", aoc.ErrUndefined
}

